### ISSUE TITLE
Filling a bucket only fills 10 units

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#10409]
Like the title says, filling a bucket from different sources only fills 10 units even if you set the transfer amount to a larger number. 
Unure if this is an issue with other reagent containers, but for the bucket it affects filling it from a sink and from the portable water tanks.
Really, the bucket should fill by the amount you select for it to fill/transfer by, and can be rather annoying for transferring large amounts of reagents as you have to keep clicking to fill it up by 10s.
Steps to reproduce:
get a bucket
set the transfer amount to 120
try to fill it from a sink or water tank

**Comment by Amunak** [comment]
That's because the sink has its own transfer amount similarly to how various dispensing devices let you choose how much you want to fill the target container. Right click on it, set transfer amount to 300 or more and you'll fill the bucket instantly.

Though I guess it would make sense if the default was set to maximum, both for sinks and for buckets since you rarely want to fill/empty those slowly.

**Comment by Greenjoe12345** [comment]
ah, didn't know of that

**Comment by Amunak** [comment]
Do you think it'd be helpful to set the default unit transfer to max for those items?

**Comment by Playbahnosh** [comment]
I think sinks and water tanks could be set to max by default. If someone wants different amounts, they can set the transfer amount manually.
