### ISSUE TITLE
Modular PDA - Engineering gas analyzer service doesn't work.

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#10505]
If you enable the gas analyzer service on your PDA it won't actually display any useful information. Holding the PDA in hand and clicking on a tile will give the "You wave your PDA over X" message but nothing else.

Figured it would work much like a handheld atmospheric scanner would. There is no way to actually see the scan as it does not go to the log.

**Comment by JohnWildkins** [comment]
The gas analyzer seems to work just fine. It's just that it only works on atmos tanks and atmospheric equipment. Only the handheld standalone analyzer works on any tile.

I'll clean up the code a little so that it's more clear what it's meant to be used on and so it doesn't give a message when used on a tile it can't scan.

**Comment by WickedCybs** [comment]
Understandable. I will go ahead and close this as it is not an issue then.
