### ISSUE TITLE
Paint is permanent on some items

### ISSUE THREAD

**Issue by BenAfflek** [Aurorastation/Aurora.3#10627]
Paint coming out of the scrubbers is a fun side project for the janitors to clean up!

If we could clean it up. For some reason, nothing but the powers of God can remove paint off of things like cameras, air alarms, glass windows, scrubbers, vents, lights, you name it. If it's not a tile, it's not ripe for cleaning.

Did I try multiple things? 
Everything in my arsenal, including an Alb. 

I tried mopping it. 
I tried using a rag.
A towel
A bucket of water.
Cleaner
Cleaner grenade
Glaring at it.

Really, nothing removes it. In an Ahelp, Even Alb tried to "dump water" onto it with a beaker. Nada.

I wonder if it's connected to https://github.com/Aurorastation/Aurora.3/pull/6656 ?

**Comment by Hockaa** [comment]
The reason dumping water on it doesn't work (and literally nothing else) is because paint just changes the color of an obj or turf when it hits ones. There's functionality for turfs (like with the above tools listed) but when it comes to objs it's different because there's a LOT of objs (like atmos pipes or clothes from the loadout) that have a different colour to their default and could potentially be annihilated of their colour by just yeeting some soap at it, or something similar.
