### ISSUE TITLE
Nymph rebalancing

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#1195]
- [ ] Health needs to be _atleast_ cut in half from 100

- [ ] Nymph attacks aren't adminlogs, they have huge grief potential behind them right now

- [ ] Nymphs have no help intent or non-aggressive click action for mobs

- [ ] Regeneration should be looked at (being brought to half health, you regen it too fast)

Other stuff to think about:

- whether absorbing blood should be similar mechanically to a leech or slime sticking to their target

**Comment by Bedshaped** [comment]
@skull132 can you make an `enhancement:rebalance` flag pls?

**Comment by NanakoAC** [comment]
I oppose the 'at least cut in half'

I support a reduction to 75 health, but no lower. They need to maintain superiority over unarmed and lightly-armed civilians to ensure their place in the world.

Their robust status adds conflict to the game, because they're a problem that can't just be stamped to death

Regeneration too, i'd say reduce by 25% at most.

**Comment by skull132** [comment]
Closed due to participant no longer being around.
