### ISSUE TITLE
Hand-tele not working

### ISSUE THREAD

**Issue by Triogenix** [Aurorastation/Aurora.3#12079]
Hand tele's portals can't actually be entered, act like a wall.

**Comment by Doxxmedearly** [comment]
It's intentional that they are solid objects. When you try to move into their space, you touch them instead of actually moving into their tile, and the teleport happens. What issues is this causing?

**Comment by Baa14453** [comment]
I had this happen during one game and someone suggested I might've be carrying a prohibited teleport object like the Nuke Disk. Not sure what I was carrying at the time sadly so I couldn't verify it.

**Comment by Doxxmedearly** [comment]
The only prohibited item right now is the nuke disk, which is intended... But also it would give you a message stating it can't go through. I've tested a few times: stepping into it, throwing items into it, entered it with a wheelchair... Everything seems to work. Need steps to recreate or to know what issues this is causing, since I'm not sure what even I should be looking out for.

**Comment by Baa14453** [comment]
Ah, I think this is caused by the Bluespace inhibitor, I was in the maintenance hallway near the vault at the time. Not sure about OP, maybe we could change the functionality so the portal doesn't open or it shows a message or something? Or my personal favourite, just gibs you

https://user-images.githubusercontent.com/9057997/123258350-2f3f1b00-d4eb-11eb-877a-59e04d6e69ab.mp4

https://user-images.githubusercontent.com/9057997/123258360-30704800-d4eb-11eb-9ee1-9e8b776591eb.mp4

**Comment by Doxxmedearly** [comment]
Thaaaat makes sense. Okay yeah. Will have to look into changing that behavior, thank you! That's a huge help.
