### ISSUE TITLE
One normal coin can buy many things, but with a time to use.

### ISSUE THREAD

**Issue by bravox2011** [Aurorastation/Aurora.3#121]
An example, I was walking around my department with a silver coin, I put it in a cigar vending machine, I was able to bought 5 cigar cases, after that I was going to primary tool storage to buy a insulated gloves with the same coin, but the coin just  dissapeared from my hand, I tested it a lot of times.

**Comment by Akrilla** [comment]
Were the 5 cigar cases usable?

**Comment by ArcBotSS13** [comment]
@bravox2011 Was there cable coil attached to it?

**Comment by skull132** [comment]
The issue is in the coin's `Destroy()` proc.

The coin is deleted from the machine using `qdel()`. At which point, the coin is deleted only once the garbage collector gets around to it. Which can take a bit, permitting user action in the interim.

The solution is to update the coin's own `Destroy()` proc to check whether or not it's in the machine, and to then unassociate itself immediately. Alternatively, have the original proc that calls `qdel()` on the coin do the unassociation for the coin.
