### ISSUE TITLE
Randomly went blind.

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#12784]
Round: cfa-aN9q
As: Lily Walker (FlamingLily)

It occured while I was in engineering, had a full (minus magboots) voidsuit on, and ait was mid-radstorm/blowout. I suddenly got "You can't seem to see anything" with no other messages, and went blind a few seconds later. After the radstorm ended, I was taken to medical with, according to the doctors, no radiated particles, no eye damage, and no brain damage.

Medicine didn't work, eye transplant didn't work. I'm not the most familliar with Aurora code, but I'm fairly sure this is a bug.

Chat log can be provided if needed, relevant section below

>  [Common] Lily Walker says, "Well. I do."
> Lily Walker says, "Well. I do."
You can't seem to see anything.
>[Engineering] Lily Walker says, "Agh."
>Lily Walker says, "Agh."

**Comment by aleksix** [comment]
Seems to be a genetic disability caused by radiation. Voidsuits offer resistance, but not immunity, from radiation. Rad particles metabolize, so the doctors failed to find any. It also doesn't do eye damage, simply makes the screen black.
From the sounds of it, you got an extremely bad roll on radiation mutation and doctors who didn't know about genetic mutations. 1 unit or more of Ryetalyn fixes those, though.

**Comment by Alberyk** [comment]
Not a bug.

**Comment by FlamingLily** [comment]
> Seems to be a genetic disability caused by radiation. Voidsuits offer resistance, but not immunity, from radiation. Rad particles metabolize, so the doctors failed to find any. It also doesn't do eye damage, simply makes the screen black. From the sounds of it, you got an extremely bad roll on radiation mutation and doctors who didn't know about genetic mutations. 1 unit or more of Ryetalyn fixes those, though.

I feel like I had some of that during the round, not sure.
