### ISSUE TITLE
Tajaran night vision is broken

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1350]
This has been a long-present issue.

Tajara are supposed to have night vision, but currently they'll only see as well as humans unless they're wearing meson glasses (or anything that puts a colored overlay on vision, I believe), in which case they see exactly like night vision goggles.

**Comment by LordFowl** [comment]
As is the case with Unathi (3), Vaurcae (8), slimemen (3), Shadows (8), and Skeletons (8).
If I may be so bold as to say, this probably could be fixed in the rawest sense of the term, but it won't be fixed unless one of the developer's becomes a lunatic (more so than usual.) The current object-based lighting system is totally incompatible with darksight, and thus we'd have to tear it all up and figure out where it goes.

**Comment by skull132** [comment]
This is down to BYOND's own vision flags, unfortunately. Fixing it might require a metric tonne of refactoring, or may not even be worth it.

**Comment by MarinaGryphon** [comment]
#9990 may have fixed this?

**Comment by JohnWildkins** [comment]
looks like it
