### ISSUE TITLE
Mid-round AI does not slave round start borgs

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#136]
Round start borgs will remain unslaved from an AI, even if one latejoins. It can be rectified in robotics, but I'm fairly certain there would be systems in place to automatically slave borgs to any AI that takes up the core.

**Comment by Ryan784** [comment]
If Borgs are not automatically slaved to the current AI when created/on spawn, that is a bug. Is that what you mean by this?

Otherwise if you are referring to the fact that Borgs are unslaved if there is no AI present on creation/spawn, that is actually a feature.

**Comment by CakeIsOssim** [comment]
I'm referring to borgs being slaved to a roundstart AI, and that AI going to AI storage. The borgs then lose their lawsync. If another AI joins, it doesn't slave them to that new AI.

**Comment by Ryan784** [comment]
Yes, Borgs are slaved to their initial AI. If another AI is created or joins, the Borgs are not automatically synced to the new AI due to the fact that, if there were two AIs present, this would cause a conflict of who is the Master of who.

Their lawsync can be fixed manually however, like you said. But Borgs not automatically syncing to a new AI is indeed an intended feature.
