### ISSUE TITLE
DEV: Game ticker is not updated after initialization pass

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#1365]
The initialization pass happens in code/controllers/master_controller.dm around line 47 
http://i.imgur.com/laR5P8s.png

This initializes all the objects in the game after they've spawned.
Any objects which spawn before this - mostly those mapped in - will defer their initialise proc until then
See atoms_movable.dm
http://i.imgur.com/WEOvWhm.png

The problem though, is that there doesn't seem to be any inherent link between the initialization pass and the game ticker. It doesn't set to GAME_STATE_PLAYING until sometime later, roundstart i believe.

That means that any objects which spawn between the initialisation pass, and roundstart, will **never** run their initialise proc. They defer it for a time which has already passed. This is the cause of many problems with cargo, and will break future work on my research system too. We need a solution to this.

My first idea is to just add a simple global var, objects_initialised. Set it after the initialisation pass and check it in atoms_movable/New. This should work and will yield an infinitessimally small performance increase but it may have unforeseen consequences by allowing objects to initialise during ticker states that they never have before.

**Comment by skull132** [comment]
I have a better idea.

The random object spawners only spawn shit in their initialize() proc, right? So, write this in:
```
    if (ticker && ticker.current_state < GAME_STATE_PLAYING)
        A.initialize()
```

Alternatively, make it a ticker variable. Why ticker variable? Because it makes sense for it to be in the ticker. And then just alter the if in atom/movable/New() to be:
```
/atom/movable/New()
    ..()
    if(auto_init && ticker && ticker.objects_initialized)
        initialize()
```

One note. You need to set `ticker.objects_initialized` to `true` **before** the for loop that initializes them. Otherwise the bug will persist, due to chained calls.

**Comment by skull132** [comment]
Testing results, pass 1.

Ticker variable is a no-go because the ticker isn't reliably created before objects. So global variable is a go. the plus side of this is: it'll minimize `if (ticker && ticker.objects_initialized)` to `if (objects_initialized)`.

Secondly, the speed increase of the global object initialization is 6 whole seconds on average. From 9.5 to 3.5 seconds.

However, there might be a hidden cost associated with this in the world/New() proc, which is the time in which the server is completely unresponsive. I'm currently looking into profiling that. If the cost is not noticeable, then we're a go for this.

**Comment by skull132** [comment]
Profiling results. 80.5 seconds of CPU time with the proposed setup. 79.9 seconds of CPU time with the current setup. Increase of .5 to 1 second, basically, to the world/New() proc, while reducing ingame init by 6 seconds. I would say that's worth it, so I'm going to go ahead with it.
