### ISSUE TITLE
Spriting involving missing limbs is wonky

### ISSUE THREAD

**Issue by LordQuailius** [Aurorastation/Aurora.3#140]
Particularly, when looking from the side it looks like the hand is still there, and you can still wear both gloves some how.

https://i.gyazo.com/2c2ef78349d47976f9c5de389b97eb1e.gif

https://i.gyazo.com/9426bafe5acdc9a6382b97ee29a9f035.gif

**Comment by Alberyk** [comment]
The gloves is due to an update which did allow people without a hand or foot to still wear gloves and shoes.

**Comment by skull132** [comment]
There's no good way of doing this, other than duplicating all sprites for left and right hand respectively (might be able to get away with only doing one side, and mirroring, at which point you'd be blooming the number twice, instead of three times, but still, it's a large amount of sprites). Considering that the amount of sprites a .dmi can hold is limited, it's a little tricky to manage.

**Comment by NanakoAC** [comment]
@skull132 Actually this may be possible with a properly constructed and blended overlay image. i have a theory, if i'm right it would take only a couple new sprites to fix

**Comment by SierraKomodo** [comment]
Another thought would be to split gloves and feet into separate 'glove_l', 'glove_r', 'shoe_l', 'shoe_r' sprites. For people without missing limbs, it layers *_l and *_r. If you're missing your right hand, glove_r isn't used. You're still increasing sprite count, but theoretically only doubling the number of glove and shoe sprites. 

The code behind this should theoretically be a little easier to manage as well.

**Comment by dapocalypse** [comment]
Your putting the empty glove on your hand stump.
