### ISSUE TITLE
Borgs cannot be placed into cyborg storage by 3rd party

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#1510]
Dragging and dropping, shoving, and various other non-destructive coaxing methods were used but the borg refused to go into storage.

**Comment by NanakoAC** [comment]
fixed by #1588 

There are two possible explanations for this, i added code to cover both.

1. The borg in question was afk but not logged out. i added an AFK check to it.

2. There was a runtime error that caused the storage pod to crash while removing its previous occupant, that would make it get stuck with a robot inside and not accept more
