### ISSUE TITLE
IAC Ship Issues

### ISSUE THREAD

**Issue by ArchitectMneme** [Aurorastation/Aurora.3#15433]
- No spawnpoint for the IAC Technician role
- This error "ADMIN LOG: Cryopod in IAC Rescue Ship Dorms could not find control computer!"

I think that's all I've seen but I'll update this or post a new issue if I find any more.

**Comment by LoreCoder** [comment]
> * No spawnpoint for the IAC Technician role
> * This error "ADMIN LOG: Cryopod in IAC Rescue Ship Dorms could not find control computer!"
> 
> I think that's all I've seen but I'll update this or post a new issue if I find any more.

Regarding the initial issue, https://github.com/Aurorastation/Aurora.3/pull/15424 should have fixed the issue with there not being available spawn points for the Technician role (if it is still occurring in rounds do let me know). As for the other issue, I believe that's because there's no cryo oversight console, however since it's an off-ship I'm also unsure if any is needed.
