### ISSUE TITLE
Certain jobs are missing sechud icons

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1620]
This is a generic titled bug report in case I find there's multiple jobs with this issue. At the moment, this is an issue for the 'Gardener' job title.

**Comment by skull132** [comment]
Most alternate titles lack job icons, because the system is set up in a dumb manner. It looks for the specific job, so in order to get icons, you either need to duplicate them with different names, or to force them to use their parent's name.

Both are kinda meh in terms of a solution, though the former is possibly more preferable due to reasons.

**Comment by Geevies** [comment]
Die, sechud, die.
