### ISSUE TITLE
[Bug]: Broken Leg/Foot Pain Too Easily Causes Heart Stop

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#16405]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Away Site

### Describe the issue

Receiving a broken foot or leg while mining is basically death if you're a miner. The pain builds while you aren't moving to the point that your heart will stop from pain shock and you'll die. Even with perconol/inaprovaline ingested in the stomach isn't enough to help (and mortaphenyl ingested on a different round). 

Splinting is usually not an option as you can't splint over a voidsuit, and getting a RIG involves mining for points in the first place.

### How to reproduce

1. Get a broken leg/foot. Miners generally do this by getting attacked by reavers/eels
2. Try to make it back to the Spark

**Comment by io-util** [comment]
So, technically speaking this is not _really_ a Bug, since it is part of the medical code and totally intended that if you keep on walking with a broken and not splinted foot you generate a lot of pain and constantly fall over. Now as you already mentioned, yes, with a voidsuit in the way splinting is not possible and you cannot just _take it off_ in 9 out of 10 cases. Painkiller medication will not help you either if you are actively walking or have done so. The only way you are going to survive it is with a miner buddy carrying you back to the Spark or splints on your foot.

Now what you could do is exempt voidsuits as a whole or just mining voidsuits (althought that would be a wonky solution) from being unable to apply splints to them. Although, that is a rather big balance change and something that Developers / Admins would have to agree to, I guess.
