### ISSUE TITLE
[Bug]: Intrepid Airlock Doesn't Cycle Properly

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16546]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Intrepid

### Describe the issue

The interprid entrance airlock does not cycle properly, despite closing the airlocks as normal the vents simply don't work and don't fill or syphon gas

### How to reproduce

Try to cycle the interprid back entrance airlock

### Round ID

N/A

### Staff ckey

N/A

**Comment by Leudoberct1** [comment]
Have looked into this myself. It CAN cycle properly, the issue is that you have to press it on all three docking ports on the Horizon, which obviously is not feasible. I have tried messing with the values to link them up, but they seem to ignore the master_tag value and do not link together. Unsure if this is an inherent bug with the multi docking port objects.

I tried swapping it to just a single controller inside the chamber itself. This allows it to cycle properly, but then the Intrepid does not dock with the Horizon properly. I cannot figure out a way to stop it doing that.
