### ISSUE TITLE
[Bug]: You can no longer become a pAI

### ISSUE THREAD

**Issue by Colfer1** [Aurorastation/Aurora.3#16599]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Submit-pAI-Personality does nothing. Clicking it gives no feedback, its a seemingly dead verb, tried typing the command in terminal to no response, tried reconnecting multiple times to same issue, tried refreshing TGUI to no response

Ideally, clicking it opens the menu to submit yourself as a pAI, which is the only way to can become one through normal gameplay, this means pAI's aren't possible to have because nobody can play them.

My byond version is 514.1589 if that helps
Asking another person to click the verb resulted in the same response of "Nothing happens"

### How to reproduce

1. Click submit-pAI-personality as a non-admin ghost in the ghost tab
2. Nothing happens when you do

### Round ID

coz-cx7U

**Comment by NonQueueingMatt** [comment]
Can't replicate locally or on server
![immagine](https://github.com/Aurorastation/Aurora.3/assets/13016572/50b94a03-9f42-4a2b-9ec8-1cf2f9bc5a8a)

**Comment by witchbells** [comment]
been running a few tests since seeing matt's post

after verifying that 'submit pai personality' still did not give a popup window, i ran through a couple common "fixes" to see if it was on my eye
![pai](https://github.com/Aurorastation/Aurora.3/assets/76234372/1ec546e7-3368-46d3-8860-9d5f8a11301c)

1. clear cache 
2. no popup

1. downgrade to the newest stable version of byond, clear cache
2. no popup

1. clear ie/edge cookies and cache
2. no popup

this prompted me to run a few tests with melaria last night who _did_ get the popup window, was able to configure the pai personality and join with no issue. since then i've been trying to verify with other people in deadchat to see if anyone else was able to submit a personality (party-cactus, maniacalfowl, coolsortiebro just today) and none were able to submit.

**Comment by FluffyGhoster** [comment]
Is this issue still present?

**Comment by FluffyGhoster** [comment]
Seeing as I see people playing as pAI, and without any reply to indicate otherwise, I'll go ahead and mark this as solved

If the problem is still present, feel free to reopen it
