### ISSUE TITLE
[Bug]: Bots detection range and maybe something else is borked

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16748]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Making bots is nowdays nigh useless since if you were to make a farmbot for example for hydroponics it won't take care of all the plants because it simply dosen't detect them after a certain range, and even those it is taking off will eventually die because after a while the bot simply doesn't want to work anymore.

while cleaning bots won't patrol the ship and simply stay still until something dirty shows up on it's field of view

### How to reproduce

make a bot, set it free in hydro full of seeds, watch it strugle, watch it give up hope

### Round ID

N/A

### Staff ckey

N/A

**Comment by Doxxmedearly** [comment]
The cleanbot issue is due to the Horizon lacking navbeacons. Those would have to be mapped in for the cleanbot to follow a route; alternatively, someone could change their behavior to wander randomly, though I'm unsure how well that would go.

Unsure about the farmbots. Possible they're getting stuck on an impossible-to-reach target. Again.

**Comment by FluffyGhoster** [comment]
The Machinist can place down and configure navbeacons for the cleanbots to patrol now
