### ISSUE TITLE
Lighting engine graphical errors

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1683]
Lighting engine seems to be creating large blocks of darkness despite the presence of light sources affecting the tile. Introducing light sources doesn't appear to have any effect, and VVing of the overlay shows the area is being registered as dark - likely error in corner calculation.
Bug likely introduced by commit 1d5287dad0e691dfde715a2c76017d80a1dcd774.
![2017-01-30_22-47-30](https://cloud.githubusercontent.com/assets/7097800/22452631/1d3d8a6c-e73e-11e6-8c4d-02852260f1e1.png)
![2017-01-30_18-32-35](https://cloud.githubusercontent.com/assets/7097800/22452633/20322e4e-e73e-11e6-9e1a-3bf2e41532b5.png)

**Comment by skull132** [comment]
Issue identified. lighting_source.dm, line 102-ish. `if (world.tick_usage > TICK_LIMIT || !ticker)`. Ticker exists in pregame lobby, created by the MC somewhere half way through the pregame setup stage. This explains only a random selection of lights not updating.

Solutions:
* Jiggle order of operations around so that ticker is created before INTELLIGENT_UPDATE is called out in the pre-baker, and use a check of this: `ticker.current_state == GAME_STATE_PREGAME`.
* Use a global boolean, like `var/pre_baking = FALSE`. Set it to `TRUE` at the start of `/proc/initialize_lighting()` and to `FALSE` at the end of it again.

First is kind of preferred, because. Well. Less global variables is gooder always.
