### ISSUE TITLE
[Bug]: Psionic Shop Point Gain

### ISSUE THREAD

**Issue by TMR-SS13** [Aurorastation/Aurora.3#17012]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Whenever I exited the Srom as a traitor psionic (Tajara), I gained 10 points in my psionic shop for some reason. This, naturally, is quite broken! I didn't use the Srom afterwards, but it's very easily abusable for infinite psionic powers, especially given the prevalence of sedatives in dealing with such antags.

This could be related to a secondary issue, though, where I somehow laterolled traitor while in the Srom, despite already being a traitor. This did not dupe telecrystals/bluecrystals, and didn't provide me a new uplink code, just the announcement that "You are a Traitor" in big red text.

### How to reproduce

1. Use Psionic Jumpstarter
2. Enter Srom.
3. Exit Srom.
4. Gain 10 points.

Secondary
1. Enter Srom on autotraitor with traitor active.
2. Late-roll traitor (???)

**Comment by io-util** [comment]
After testing, you also regain all of your points if you reconnect, because:

```
/mob/living/LateLogin()
	..()
	if(psi)
		psi.update(TRUE)

```

LateLogin() gets called when you reconnect and also called when you Awaken from the Srom. The update proc sets your points again.

https://github.com/Aurorastation/Aurora.3/blob/master/code/modules/psionics/mob/mob.dm#L4-L7
