### ISSUE TITLE
If you erase digital records/manifest entries, then the physical records get erased too

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1712]
![image](https://cloud.githubusercontent.com/assets/19973802/22616864/8b876138-eb1b-11e6-9afa-bcfb85798369.png)

The physical records cabinet is a bit weird with how it magically generates new entries as people board, but if they disappear along with the digital records if they get manually deleted then there isn't too much point to its existence.

**Comment by skull132** [comment]
Physical records are a lie. The records cabinet is actually a computer. _Your whole life has been a lie._

Anyways, it's an accepted side-effect of not fucking with shit. The alternative is that paper records only exist for people who were there at round start, because lolteleport is odd, if only applied to one side of it.

**Comment by SierraKomodo** [comment]
@skull132 Would a possible option be to replace the current records cabinet with some kind of pseudo-console disguised as physical records that pulls directly from the records on the database instead of in-round records?
