### ISSUE TITLE
Blobs can attack you through window panes

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1894]
The pain in question was fully secured to the floor and there shouldn't have been any way for the blob to hit me (There was a line of the panes)

**Comment by LordFowl** [comment]
Related to the issues of blobs being able to pull people from diagonals when the person cannot hit the blob (because of being surrounded otherwise by dense objects). Blobs should stop using a basic range check and should use a more robust set of paremetres, such as those used in human clicks, to check for proper adjacency.

**Comment by NanakoAC** [comment]
i will fix this

**Comment by Doxxmedearly** [comment]
This is no longer relevant since we have ported a new blob.
