### ISSUE TITLE
Roboticists Hate Him: IPC Achieves Near Immortality With One Simple Trick!

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#1901]
For some reason, prosthetic limbs do not contribute to the total health value of a mob, which may or not be intended depending on how powerful you view the things you can literally select at round-start should be. This is not a _huge_ issue until you consider the fact that IPCs are all prosthetics, including their heads.

What this means: IPCs cannot be killed by any damage to their limbs, including their head, unless such damage actually severs the head. This means that killing an IPC is pretty much only possible when aiming for the torso.

This also gives IPC's a very misleading indication of how healthy they are. Even if _every_ one of their limbs was completely damaged, but their torso was fine, their HUD would display them as perfectly healthy.

I don't really see any need to complicate this: Just make prosthetics count for total mob health again. Simple stuff.

**Comment by NanakoAC** [comment]
i dont think its the right approach, personally. 

Prosthetics not counting towards total health is fine. Hell i'd even say extending that to organic people wouldn't be bad.  Getting stabbed in the leg is only likely to kill you from blood loss, it contains no vital organs

The head is a problem though. If we dont already have it, add an essential flag for external organs, and any with that flag should count towards total health (head and torso)

**Comment by Spoopy11** [comment]
Got to agree with Nanako. Why would repeatedly smashing in someone's prosthetic arm kill them?

**Comment by LordFowl** [comment]
Because prosthetic arms are something you can acquire at round-start, and them not contributing to total health constitutes a severe unbalance. Furthermore, it is highly unlikely you can kill someone through their arm, as the arm reaches a damage threshold.

Limbs, prosthetic or otherwise, represent part of the body and should be treated as such. Their primary advantage is not contributing to bloodloss and it should remain that way. Their destruction inhibits your wellbeing, and thus should be represented.

Finally, for IPCs it is absolutely necessary that all limbs contribute to their total health. They are part of their body and not merely prosthetics.

Do not confuse painlessness with wellbeing - if health was a measure merely of pain then Dionaea and IPCs wouldn't have health at all.

**Comment by OneOneThreeEight** [comment]
Oops.

Apply an exception where if an IPC takes chest/head damage it applies to their full health, but they can live without their other limbs?

**Comment by LordFowl** [comment]
As I've stated, you can already live without your other limbs, because unless I guess you lost all four limbs that damage would not be lethal unless there was bloodloss, which prosthetics don't cause - especially IPC prosthetics. The loss and damage of this limb should still be accounted for in the total wellbeing of the mob, tho. Consider also that an IPC has no way of knowing how damaged their limbs are without a scanner, because their HUD doesn't update when their limbs get damaged because their limbs technically aren't part of their body.

**Comment by OneOneThreeEight** [comment]
Self-examining (both by way of help intent self-click and shift-clicking self) permits them to see what parts of their chassis are wounded. To what extent, they can't tell, besides shift-clicking giving a general idea on what might be irreparably damaged on the field. Still pretty limited as you said and only barely helps.

The HUD only visually updates for races that experience halloss changes, to which IPCs are completely unaffected.

The issues I see in particular is the lack of clarity behind taking damage without having clearly analyzed what got hit where and how, and the fact that IPCs live forever because their everything is synthetic and doesn't push towards their health threshold, which is strange.

It does bring to mind some interesting things that can be done, but I'd say a good fix for now is making it so that the chest and head have exceptions wherein dealing damage to those specific organs causes actual health damage and forcing them to collapse, not so much by "pain" but it can be excused by the fact that the integrity of a chassis can't take so much damage before eventually falling over.

**Comment by SirFruitcakes** [comment]
A good way to make this work better would be to make IPC limbs shudder and spark automatically at a certain damage threshold (It already does, but I don't know when or why) which could spread burn damage to their Torso periodically. But, I will say, currently, IPCs are just about unstoppable, i've seen a lot of silly stuff done by them lately. This really does need some sort of fix, IPCs are unstunnable, near impossible to make collapse without EXTREME damage, and near unkillable. I don't think EMPs even work correctly on them right now. Even Dionae are more flawed than IPCs with all of these issues, because Dionae can just get flashed, no way to disable for IPCs. Literally the only way I could see stopping them ATM is an absurd amount of lethals aimed at the Torso (And HOPE it hits the Torso) or multiple explosions. PLEASE GOD DO SOMETHING ABOUT THIS.

**Comment by Geevies** [comment]
Fixed, I believe.
