### ISSUE TITLE
[Bug]: Sol Navy Recon Ship Crewmen Spawn with Engineering Gear

### ISSUE THREAD

**Issue by beepbopbeepbop** [Aurorastation/Aurora.3#19263]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

The Crewman and Chief ghostspawns for the ship spawn a full engineering belt and brown engineering webbing, despite the fact that they are likely going to either be generic soldiers or medics. The optional engineering gear is also available on the ship, making them spawn with this useless.

### How to reproduce

1. Spawn as either a Crewman or Chief on the Sol Navy Recon Ship.
2. See the results.

### Round ID

ctW-bXvy

**Comment by TheDanseMacabre** [comment]
I'm the person who added this ship and therefore did the outfits for these ghostroles. This is not a bug, it is intentional. The people on the recon ship are not "generic soldiers or medics", they are navy sailors and their primary responsibilities have to do with the maintenance and operation of the ship. If you don't want to wear the webbing or the belts, the lockers in locker room have other options for you to allow you to specialize.
