### ISSUE TITLE
Custom Loadout Lunchbox doesn't spawn when you pick it

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#1968]
How am I going to eat without my immersion?

**Comment by Alberyk** [comment]
I tried and they did spawn fine in the server, you will need to give more details on what happened.
![lunchbox](https://cloud.githubusercontent.com/assets/11579997/24227527/78004062-0f4c-11e7-90ea-4cc6930452a8.png)

**Comment by OneOneThreeEight** [comment]
Not a bug relating to lunchboxes. This is often because you need to save the slot after adding the custom loadout items you want, and then reload the slot before joining. Morein an issue with saves not being reliable in actually saving, and you need to reload the slot to make sure they work properly.

**Comment by ToasterStrudes** [comment]
![image](https://cloud.githubusercontent.com/assets/24210359/24275423/a3d63c78-1005-11e7-9e95-c69ff443d314.png)
... oh
