### ISSUE TITLE
Unarmed individuals unable to defend against bears.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#1971]
https://i.gyazo.com/c7ff8a4ed1b8a7b279d72482fae91399.png

My laser ran out of shots, and I attempted to defend myself with claws after being cornered by it.  This is when I discovered that even in harm intent, you cannot proc an attack on a bear without a weapon in your hands. You just helplessly poke the bear while it mauls you to death.

I highly doubt this intentional, and if it is, it definitely needs to be made not a thing.  Dangerous organic mobs attacking you need to be targettable with attacks.

**Comment by Lohikar** [comment]
This applies to all `simple_animal` as far as I know; no kind of unarmed attack works.

**Comment by NanakoAC** [comment]
this is intentional, though perhaps an oversight. Its simply a matter of inappropriate text. Poking the bear does damage it, although not by much, 3 is the default

More complex melee combat, like using your species' claws, is not supported with simple animals. thats maybe something we could work on, but the lack of it isnt a bug.
Attacking simple animals works with predetermined damage values and attack text. Bears just have an odd text and a low damage. Normalizing them a bit would probably make sense
