### ISSUE TITLE
[Bug]: R&D development console does not update when category is changed.

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#19944]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When you use the R&D console, you often want to filter the products by category. However, changing the category only affects the interface if you exit, then enter, the view you are working on. It is a bit cumbersome and seems unintentional.

### How to reproduce

1. Open protolathe or circuit construction menu.
2. Change the category.
3. Nothing ought to change until you exit and enter again.

### Round ID

cvS-djLb

**Comment by FluffyGhoster** [comment]
The "I have searched the bug with a few keywords, and I confirm this bug was not yet reported." is required to be checked before submitting a bug report for a reason

The keywords "console", "research", "update", "category" and "change" returns the PR #19077 that tracks this bug

Closing in favor of aforementioned PR
