### ISSUE TITLE
Mechs cannot be used if they have maintenance protocols active, and maintenance protocols are forbidden from the control panel

### ISSUE THREAD

**Issue by moom241** [Aurorastation/Aurora.3#2009]
When repairing a mech in cargo, it comes in a state where maintenance protocols are not permitted, but it is already stuck in maintenance mode. Maintenance mode keeps it from moving and acting, and also keeps it from changing permissions on maintenance protocols. Maintenance protocols can also not be shut down in this state, because they are forbidden from the mech control screen.

**Comment by NanakoAC** [comment]
in this state you need to go inside the thing and enable maintenance from the internal controls. Its a security measure so that someone from outside can't disable a giant robot by pressing some buttons

However it is a bit of an oversight that there's no way to override the access controls. If you get an exosuit in that situation there's nothing you as a roboticist can do. I wouldn't really call this a bug so much as a hole in functionality
