### ISSUE TITLE
Polymorph messes with antags

### ISSUE THREAD

**Issue by TrickingTrapster** [Aurorastation/Aurora.3#2047]
If, for whatever reason, you want to have more antag types than just wizard, for a gimmick or something, polymorph will screw over the secondary antag. A vampire lost his vampire powers to this, but was still flagged as vampire. Couldn't even drink blood, glare or hypnotise. Yet to be confirmed for other antags like changelings but I'm betting it can happen still.

**Comment by Kaedwuff** [comment]
As the vampire affected, I will give some testimony that may or may not help.

I still had the vampire tab, but the only thing displayed on it was the the 'vampire help' button, and all my other vampire power verbs were missing.  I couldn't manage to find commands to simulate them either.  Originally, I still had my blood total/usable, but after Nursiekitty toggled my vampire status, I continued to have no powers under the vampire tab, and my total blood measurement had vanished entirely.

If I had to guess what is happening, the process of being turned into a mouse/corgi/whatever fucks up the mind variable that stores vampire information in a way that isn't even properly cleared out if you try to de-antag the character.  I am pretty sure the entire mob has a sort of dangling, nonfunctional vampire variable afterwards.

**Comment by cha0s5150** [comment]
I was polymorphed as changling and can say it had no affect on my ability to use changling abilities. I still stung the wizard and then got polymorphed again and flashed and cabletied and kidnapped. No problems with wizards polymorphing changling.

**Comment by Kaedwuff** [comment]
After some testing on Lohikar's server, I think I have figured out the problem.  The issue with vampire powers appears to be that anything that changes the mob data causes you to to 'forget' the verbs granted to you (including those you get upon being vampire for the first time). Now, as far as I can tell, the game checks your current powers every time your blood values change /due to drinking blood/, and awards you access to those powers once there is a blood total high enough to unlock them.  However, it only does this check during blood drinking, as far as I know, and with losing access to that verb you can no longer get it fixed.

It also is worth noting that the traitor panel /does not remove vampire mind variables when you toggle it off./  The only thing that happens is you receive a message saying you are no longer a vampire, but you retain all vampire abilities.  This is why toggling vampire does nothing   (thralls are the same way, being a subset).

A similar problem occurs whenever you do anything that changes your mind to another mob, such as via cloning.  I am pretty sure a body swap would also fuck it up.
