### ISSUE TITLE
Wheelchair Bug

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#252]
You can push people out wheelchair with Help Intent.

**Comment by inselc** [comment]
Is this still a thing? Could not reproduce this with the latest master and dev builds.

**Comment by skull132** [comment]
I'm uncertain. I know a patch was run against this issue by Nanako at some point, a month or so after her movement rework was implemented. It's possible she didn't flag the issue properly because she never used keywords on git.

I haven't seen nor heard of this in a long time, and I doubt it's because our admins are bloodthirsty fiends towards bug abusers. So, I'll just close this until someone manages a way to reproduce.
