### ISSUE TITLE
[Newmap] Stacking machine deletes itself

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2636]
```
DEBUG: Stacking machine tried to process, but no console has linked itself to it.
```
![2017-06-06_16-27-24](https://user-images.githubusercontent.com/7097800/26852785-0a407014-4ad5-11e7-87ae-f3c16d3d4dbc.png)

**Comment by Arrow768** [comment]
The stacking console has a machinedir variable to specify in what direction it should look for the machine.

If it cant find the machine in that direction, the console doesnt link itself to the machine and therefore the machine qdels itself when it tries to process.

Can be fixed by changing the machinedir variable of the mapped in stacking machine console.
Alternative would be to change the way the stacking machine links to the console.
