### ISSUE TITLE
pAI Bugs (Crew Manifest, Medical HUD)

### ISSUE THREAD

**Issue by bug924411** [Aurorastation/Aurora.3#2771]
**Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.**
* **Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!** N/A
* **Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.** 
Medical HUD: Only the red cross appears, not the green health bar.
https://i.gyazo.com/32d5554bea1564805372e88f034c0748.png
Crew Manifest: Error report comes up
https://i.gyazo.com/4ad9cb1b7bbb392c7dea8ada78071a76.png
* **Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!** Tried clearing cache, restarting, etc. Nothing worked, same errors persist.
* **All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.** Admin: Pikl   Round ID: bO4-cLXi

**Comment by skull132** [comment]
The former is not a bug.

Medical HUDs in our code do not show the healtbar if the subject is at 100% health.

**Comment by bug924411** [comment]
I found this out later on, however the crew manifest bug is is still a problem.

**Comment by gelza1** [comment]
As of two minutes ago, the crew manifest is still bugged.

When you select "Crew Manifest" from the "Software Interface", a window titled "Crew Manifest" opens, with an "Initiating..." bar underneath.  However, moments after the window opens, an error (titled "Message from webpage") pops up: "ERROR: An error occurred while rendering the UI: Unable to get property 'length' of undefined or null reference."  Once you click the "OK" button to dismiss the error, you have less than a second to close the window, else the error will pop back up.

When I ahelped, Juani2400 suggested I report the bug here.

**Comment by tzeneth** [comment]
The manifest when I activated it gave me the same error and added someone with a Null mark on them instead of naming them. Seemed random who was selected for that issue when I opened the screen multiple times.

**Comment by Karolis2011** [comment]
Duplicate of #2124
