### ISSUE TITLE
Surprisingly low damage of plasma cutter

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#2879]
Human was hit 9 times in the arm, his arm hardly even crunched. "He is wearing a warden armor vest". No information about damage tweak was logged on the changelog list. By an admin response, it's about 15 burn damage per hit. Somehow, the armor vest had countered 135 points of burn damage to the ARM in total, not just not downing the opponent, but leaving him a chance to go across the station and start to break up on cameras, not care about seeking for any medical attention at all. That's not even brute damage to be countered by an armor vest, that's not even something in the vest itself, to protect arms/legs. That's highly kind of suspicious. Vest is just a vest, covering a body. No way it can block so much damage

**Comment by HetNeSS** [comment]
/obj/item/clothing/suit/storage/vest/warden
	name = "warden armor vest"
	desc = "A simple kevlar plate carrier belonging to Nanotrasen. This one has a silver badge clipped to the chest."
WHY THE FUCK it blockes burning damage, and blockes it better than a basic sec armor vest? And covers the whole body? That's the thing I want to know

**Comment by Fire-and-Glory** [comment]
I would imagine it blocks burning damage because, security armor is a lot about shielding you from friendly fire from your mate's lasers.

As for body-coverage, the general rule of security's fashion clothes is that all armor variants available to that specific job in security have the same coverage and armor values.

Both the warden and HoS have big armored trenchcoats, and their vests share the same qualities, presumably so that the warden/HoS didn't have to worry about compromising his armor because something else looked better.

It'd block damage better than a normal secvest because it is more rare than secvests, I'd presume.

**Comment by OneOneThreeEight** [comment]
You must be new here. That is our damage system. Security armor has values weighted to protect against melee, in particular. Even if plasma cutters dole out fireloss, they're treated as any bludgeoning weapon would be.

The warden vest "soaked" all that damage because you were using the plasma cutter as a melee weapon. Security armor protects a lot from melee weaponry.

**Comment by MarinaGryphon** [comment]
It also is terribly ineffective at digging, and particularly at cutting through walls, which was (one of) their main feature(s) before.

**Comment by Alberyk** [comment]
I am sure you can still hit walls with it.

**Comment by HetNeSS** [comment]
@OneOneThreeEight ok, thanks for the explain. Looks valid now
