### ISSUE TITLE
Area Air Control - Huge scrubbers on toxins don't seem to do anything [oldmap]

### ISSUE THREAD

**Issue by cl234** [Aurorastation/Aurora.3#2885]
https://puu.sh/wyUC9/414a3cc421.png

The scrubbers 2, 3 and 4 don't seem to have any pressure or flow rate, despite being active and the room filled with phoron.

Furthermore, there's no indication on the computer as to whether the scrubbers are on or not, other than the green light on the devices themselves.

**Comment by HetNeSS** [comment]
Works fine each time for me.. There was a moment on one round where two of the science guys opened a valve on phoron tanks. Those scrubbers sucked in like 10% of room air filled with plasma in just a minute. Might be the reason is that local air alarm needs to be set up to scrub any phoron in that room.. not sure.

**Comment by cl234** [comment]
This may have been a one-off then

**Comment by Juani2400** [comment]
We have switched maps permanently. Closing.
