### ISSUE TITLE
[NEW MAP] Portable air pumps piping is connected to main air distribution pipe

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#2995]
The air distribution and the PAP piping have to be separate in order for engineering to be able to refill PAP's at a decent speed. With the current default layout the gas pump refilling the PAP's must draw air from the main distro system which is normally kept at 300 kpa by a decent Atmos tech to allow modifications through the station. This make the gas pump fill at a rate of about 4 kPa per second, which is agonizingly slower than what the setup in a normal atmospheric mapping.

**Comment by Juani2400** [comment]
With the proper upgrades, it will fill just as fast. Currently, redoing the piping in that area is not feasible unless we rework a big portion of Atmospherics. May be fixed in the future, but will not be fixed for now. As said, if you attach a pressure regulator, you will get all the flow of gas you need, quick enough.
