### ISSUE TITLE
Objects can still be lowered through catwalks on the hoist

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3123]
Objects can still be lowered through catwalks and lattices on the hoist. The clamp can be raised and lowered as if it were open space (which it technically still is).

**Comment by Juani2400** [comment]
Pretty sure this is intentional. Will let others confirm.

**Comment by MarinaGryphon** [comment]
Hm. This might be a bit tricky to fix, considering you need to be able to hoist catwalks.
I could always check for _anchored_ lattices...

**Comment by JohnWildkins** [comment]
Still an issue. Notably, objects placed on the hoist from the hand are also not properly removed from the hand, leading to item ghosts.

**Comment by MarinaGryphon** [comment]
> Objects can still be lowered through catwalks and lattices on the hoist. The clamp can be raised and lowered as if it were open space (which it technically still is).

Okay, so essentially: works as intendedish/oversight. Catwalks are not dense. You'll have to check an extra flag or throw in an istype.

Also, since when could you place objects on the hoist hook by hand? Oh God, you can drag it from your inventory, can't you? That's absolutely unintended but it can probably be handled by checking if the loc is a mob and unequipping it if so.

**Comment by deGurkin** [comment]
had this issue multiple times constructing solar panels above the Tesla, very confusing for someone who doesn't know how the system works. Took us 20 minutes to figure out what was going on.
