### ISSUE TITLE
Research R&D Mixing Lab

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#3129]
One fine afternoon, I was going to mix toxins lab and started burning stuff up in name of science. 
![image](https://user-images.githubusercontent.com/12143105/28480466-6d23bca8-6e26-11e7-9893-1d58c80f769c.png)

I noticed a major flaw in why the canister isn't picking up gas as it should be. 
![image](https://user-images.githubusercontent.com/12143105/28480527-b32969be-6e26-11e7-9457-8ef49be691fe.png)

Then, I noticed that there were no vent pump in the room as there is in the windowless closed room. 
![image](https://user-images.githubusercontent.com/12143105/28480538-c5340fb0-6e26-11e7-8a0c-be0c38643760.png)

I proceeded to inform @Alberyk that something may have been broken. He informs me that it is not broken. I informed him that something is not functioning correctly as it should be, he had not bothered to check what the issue is and shrugged me off. I figured I could make a Github report.

**Comment by printer16** [comment]
Toxins no longer operates on a "put gas in, burn that gas, and extract the same gas" set up. It now works in a much more efficient way. You place the canister full of gas you want to heat up on the port to the left of where you have the gas canister after heating up a separate gas canister inside the room. You then turn on the pump and the gas goes through the heating pipes and into the empty container where you have it currently, heating up as it does so.

**Comment by skull132** [comment]
What Printer said. We had this setup on the old Aurora iteration of the Exodus, before the baymemes of 2016. You use the port left of the yellow canister to fill the heat transfer pipes with the gas you want to heat, light up the chamber, wait for the gas to be the proper temperature in the HE pipes, and then siphon it to the yellow canister using the right pump. It's a much more advanced and pleasant setup to work with, as you remove the stupid waste gasses from your mixes.

If you know atmos enough, you'll notice that it's a U loop and you haven't hooked anything up to the starting end of it :l Which is why it's "not working".
