### ISSUE TITLE
Eye Color 

### ISSUE THREAD

**Issue by UbrPzMaus** [Aurorastation/Aurora.3#3336]
Eye color (human, character creator) will only let you set variations of green or pinkish-purple, any other color will revert to those two or black.

**Comment by NanayaSoul** [comment]
I've recently got this bug too for some reason. It happens exactly as it is said above.

Creating another character, using another BYOND Key, or even another computer on the same IP doesn't seem to change or revert as the color wheel keeps treating your base eye color as if it was 'blue' (Also an assumption made due to the 'Blue' color becoming 'Black'.) I can presume this is happening to something bound to our save files on the server's side.

I can also wonder if this is anything related to using 'mechanical', for eyes setting. The game tends to bug a lot when you have prosthetic limbs, and multiple characters on the creation, so I suggest this gets checked ASAP, as it might damage the experience of older players trying to make more characters (or even new ones, although improbable).

**Comment by Butterrobber202** [comment]
same, you have to guess which color will let you do what by spamming the HTML Color Hex.
