### ISSUE TITLE
NewVamp issues discovered.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#357]
We had our first round of NewVamp.  Discovered a number of frustrating issues.  As follows:

-Glare/Hypnotize knock over a target, but they do not prevent them from endlessly spamming resist, making it impossible to get a sufficient grab to feed.  The vampire was unable to restrain their target this way, and lost a fight due to their powers not functioning properly.
-Blood heal might be a little buggy, their blood did not seem to go down, though it might still be speeding heeling, I VV checked them.  It also doesn't heal broken bones or ruined face, or brain damage.  Maybe it should?
-Void Step is an extremely confusing interface, asking which tile you want to jump to, and listing things like 'O2 Floor", "Reinforced wall', and "shoreline", which makes me think it is picking random, distant things and gives the player no real concept of what their choice is going to lead them to.  This could probably be tweaked to be more user friendly.
-Presence seems to work fine, but it can't be toggled while the vampire is unconscious.  This led to it steadily draining while they were helpless in surgery.  Maybe make it automatically shut off if they go unconscious, if you don't want them able to activate it while being so?

There may be more, but they did not progress far enough in the vampire power path for it to be clear.

**Comment by OneOneThreeEight** [comment]
In relation to the first issue, have you tried using restraints or any of the sort? From a gameplay perspective it's normally wise to keep a pair of cable ties on you for that purpose.

**Comment by Kaedwuff** [comment]
That's not a bad idea, but the vampire was relatively new, and might not have even known there are such things as cable coils.  Certainly, I didn't mention it to them, because I assumed the vampire glare would disable like it's supposed to.  On the other hand, if being able to resist spam was intended, I guess I can mention it to future vamps.

**Comment by skull132** [comment]
* Glare and hypnotize use the same procs a stun baton uses to stun. May have to review and test further. Though what probably happened is the stun duration ran out.
* Blood heal may indeed be buggy. It _should_ heal bones, and it stops draining blood if it has nothing to heal.
* Void step is not meant to be used as a command like that. It's supposed to be used by right clicking a tile. If they got it opened via command prompt, then, well, that's their issue. The button should be hidden otherwise.
* Need to toggle presence whenever vamp goes unconscious, along with a few other toggleable abilities.

**Comment by nicemoreoften** [comment]
Glare and hypnotize don't stop resists, even before the stun runs out.

Void step can be used in a tab.

**Comment by Bedshaped** [comment]
Fixed
