### ISSUE TITLE
Merge Oldcode Features?

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora.3#361]
Handful of features that were left out; recall a dev saying to list these things as issues or they'd be forgotten/overlooked.
-Security hardsuit sprites
-Oldcode alcoholic beverages, most of which by Skull (and their sprites.)
-Bluecurity(?)
-Energy rifles and ziptie restraints for ERT (maybe give mercenaries/raiders zipties as well?)

**Comment by skull132** [comment]
Zipties didn't work at all. Weeee~

**Comment by Serveris** [comment]
Oh, _**dear**_, they worked fine.

**Comment by OneOneThreeEight** [comment]
Let's not also forget:
-Duckchem
-Skullchem
-Better forensics code overall

**Comment by skull132** [comment]
@Serveris 
* Hardsuit sprites may be looked into
* Beverages are in dev effective today
* Bluesec will probably undergo another public vote, because the community has changed a decent amount
* Zipties _were_ horribly broken and aren't worth porting in their old form. (They were, for all intents and purposes, resprites handcuffs. Which wasn't their point.) I tried making them work on oldcode, didn't work at all, got anger, went RIP. Energy rifles still worth it after ERT gets RIGs?

* Duckchem maybe
* Skullchem isn't coming along, because it was never finished.
* Forensics code is actually better :D . Zuhayr did a great job at rewriting it. Minus a few functionality tweaks which are already mentioned in separate issues.

**Comment by Bedshaped** [comment]
DONE?!
