### ISSUE TITLE
Borgs buckled to a chair can't unbuckle themselves

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#383]
As the title says borgs buckled to a chair can't unbuckle themselves. 

I've seen this issue mentioned a lot in chat so I thought I'd post it.

**Comment by NanakoAC** [comment]
skull has said that we won't generally be giving borgs the ability to unbuckle things because of immersion reasons (they don't have hands to undo the buckle)

but i think they should still be able to break out. Put their actuators into overdrive until the strap breaks. and they also should not be able to buckle themselves in, in the first place

**Comment by darkrising** [comment]
At the moment it's just being used to perma-buckle borgs. I don't think the belt would stretch that far on the bigger / fatter borgs anyway.

**Comment by LordFowl** [comment]
Borgs can unbuckle themselves via using the "resist" button.

**Comment by Serveris** [comment]
See above comment. They can unbuckle by using the resist verb.
