### ISSUE TITLE
Top-hat sprite issue

### ISSUE THREAD

**Issue by TheBimmer231** [Aurorastation/Aurora.3#3853]
![image](https://user-images.githubusercontent.com/22187456/32702432-1b73ea46-c7df-11e7-8495-bbb95ccf3a8d.png)
Yeah the sprite's fucked.

**Comment by Sindorman** [comment]
Where did you get hat exactly? Because sprite, and code seems fine.

**Comment by Sindorman** [comment]
Seems to be working ![2017-11-13](https://user-images.githubusercontent.com/25555314/32753659-91dcf49a-c882-11e7-852c-e9c0b066841a.png)

**Comment by LordFowl** [comment]
He is talking about the in-hand sprite, not the worn sprite.

**Comment by Sindorman** [comment]
![hand-side](https://user-images.githubusercontent.com/25555314/32807603-3f1898cc-c945-11e7-9398-9694ad19ae31.png)
![hat-back](https://user-images.githubusercontent.com/25555314/32807605-4070cbe0-c945-11e7-8f0f-5aa0ce826a7f.png)
![hat-front](https://user-images.githubusercontent.com/25555314/32807609-41e1ae22-c945-11e7-879f-c5dae72f4252.png)
![hat-hand](https://user-images.githubusercontent.com/25555314/32807610-4313ef6c-c945-11e7-8ba1-8887e6cee81b.png)
Seems Okay, or you want to change it from angled to regular?

**Comment by LordFowl** [comment]
His particular issue is with the middle sprite. You do not usually carry your hats behind your back, and even if you did it conflicts with the bottom and the top sprite, which present the hat as being carried in front of the wielder.

**Comment by Sindorman** [comment]
Okay, I will change it.

**Comment by Sindorman** [comment]
@TheBimmer231 @LordFowl I changed sprite so that you can only see part of it, as if you can see from the back part of someone's holding. Like space in between arm and your body.
![2017-11-15 1](https://user-images.githubusercontent.com/25555314/32869136-4417496e-ca2a-11e7-8868-24515444dddf.png)
![2017-11-15](https://user-images.githubusercontent.com/25555314/32869138-46992504-ca2a-11e7-867a-612c905c61a1.png)
