### ISSUE TITLE
Tesla not doing what its supposed to do.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3924]
Its been an issue here and there with the tesla. Basically, you set it up, everything is in due place, you fire it up, and it COMPLETELY IGNORES the tesla coils and grounding rods inside the primary chamber. It choses to go straight for the accelerator room, zapping the equipment and killing the people inside there.

![](http://puu.sh/ywCeO/c5e7048702.jpg)

It will respond to a tesla coil brought inside the accelerator's room, but thats the extent of it. It will not generate power, and will goof around until the containment fails and its gonna zap around on the sublevel.

**Comment by TheGreatJorge** [comment]
Maybe that has something to do with the fact it's forced on one tile? I know this may just be my opinion, but in a funny way, it looks fair for it to zap what it isn't supposted to, if you game it like that and such. Heh... Although, yeah. On the other hand, I imagine it does indicate that there are some things broken in the code...

**Comment by Pratepresidenten** [comment]
No, it has broken before with a standarized setup aswell. No modification to the containment field.

**Comment by Sindorman** [comment]
I will dig in, and try to look what is wrong there.

**Comment by Sindorman** [comment]
@Pratepresidenten I have tested Tesla Engine, it appears to be normally functioning at your set up, and in normal 9x9 set up!

**Comment by Pratepresidenten** [comment]
The containment failure due to someone fucking up the SMES settings isnt the issue here. The issue here is that the tesla ignoring literally everything in the chamber its set up in, tesla coils AND grounding rods just to zap the control room and the people inside.

Its not a guaranteed occurance, but it happens frequent enough compared to how often the tesla is actually set up.

**Comment by Sindorman** [comment]
@Pratepresidenten I know that containment is not an issue here. But it is a possible future issue, which can be fixed. However as I said it tried bot set ups, and in all cases it seemed to be working well. I did not however put a grounding rod inside PA room, that also might change something. I will see if during regular round it occurs.

**Comment by Sindorman** [comment]
I have checked it, finally managed to recreate your situation. It appears to happen only when room's APC is either out of power or has everything turned off. I will look into code to see why coils depend on APC power

**Comment by Ornias1993** [comment]
I Also hit this problem and investigated, the problem seems to be more complex than just this, its a cascade of problems.

1. The rods and coils use the APC (fixed now it seems)
2. The APC fails to charge (even with good connection to the power network) at times
3. When the particle accelerator fires in current setup on +1 power, it drains the APC super fast. +2 seems to use less power for some reason(maybe it should be put on a wire, by default or docs should be updated to include that?)

So what happens is this:
1. PA is started on +1
2. APC is drained
3. APC does not get new juice
4. APC goes out, taking Rods with it

Repairing the rods=lights issue is a big leap forwards

Till merge into master there is a work around:
- Put the APC on a line only to the main grid or tesla output SMES (not both) with lights and equipment put on "on" instead of auto.
- reset it if it doesn't work (taking out the cell, resetting the breaker)

**Comment by Sindorman** [comment]
@Ornias1993 That is exactly what I concluded. Coil rods do not directly take charge from APC, but when the `lights` are off they are being ignored as closest thing in Tesla ball. From the code wise I think it is not coils itself, but rather Tesla ball has some weirdness when it just stops detecting coils as closes object to shock, and it goes for grounding rods.

To stay safe:

- Place grounding rods in each 4 directions of Tesla ball right behind coils, at this point even if the power is out, until the containment field is up Tesla won't shock anything else but grounding rods.

- Another things as you said - in standard SMES and wire setup APC never gets enough power to charge, so just connect Tesla output to the main grid, that way it will keep SMES charged, APC charged and main grid won't drain things.

Hopefully at some point I will be able to debug the ball to see why it stops seeing tesla coils as targets, its is deep issue right now.

**Comment by Ornias1993** [comment]
I think you didn't fully understand me in regards to the SMES at least.

The APC is bugged, it WILL NOT CHARGE as it is currently placed if its connected to both the TESLA grid SMES and the rest of the grid. Which makes the TESLA unusable at the moment because you can either run the APC or power the rest of the grid.

**Comment by Sindorman** [comment]
I never seen APC not being able to charge, if you set SMES output to max and upgrade it, plus connect Tesla to the main grid going through SMES - it would charge just fine. It is not bugged, there is not bug issue there, it could be that there was power sync somewhere

**Comment by Ornias1993** [comment]
Yeah and there is your bug.

The APC is connected to the main grid, where all generator SMES (SM, Solar and TESLA) units are dumping their energy into. It should ALWAYS charge as long as there is enough energy in the main grid.

The point is: It frequently does not charge but does indicate that it has a good connection with the grid.
As soon as I cut the cable connecting the APC and Tesla-Grid SMES to the main grid, and reseat the powercell, it starts to charge again.
I tried it about 3 different times last few days on live, it just very frequently does not charge till I cut the cable and reseat the powercell. Thats not normal behaviour thats a bug.

You shouldnt even need the TESLA SMES to charge the thing, but its really unrelated to the TESLA SMES.

However, can you relate what you mean with "Power Sync"?

**Comment by Sindorman** [comment]
Tested lately, no longer a bug.
