### ISSUE TITLE
Mesons, thermals and other vision glasses are not working.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4179]
Basically, it only fully illuminates what you can see. Does not give full vision of structural integrity as it used to.

**Comment by YuriDaruski** [comment]
This also apples to people mesons and /technically/ Material scanners which will make sense in a sec. So, before the update, one could RIG-mod a material scanner and they would function like mensons, but way back even on the exodus the mensons were broken so you can't see the ores. Well if you modpress one and wear a second pair, you'd be able to see the ore. Because the material scanners see ore, but only in light, so with the night-vision like mensons you'd be able to see all the ore in the rock, even deep inside it.  https://gyazo.com/5c031765e86b28e27bcca975e52df135 This is the new view, previous to the update, aaaall of those black tiles would have been visable, and you could see the ore in them, now you can only see the outer walls and the ore of those walls only and those that are in the light. In this example https://gyazo.com/d00ce781cf940f2eabc654eb49ccf714 the ore is clearly visible ahead of the character while using both material scanners and the modded material scanners/mensons. However, turning 90 degress north, facing the helmet light away from the ore and therefore taking it out of the light, https://gyazo.com/e33cf9012c2f40656af9aa53af78d8c6 The ore is now hidden from sight, when before the update, one would have still seen it. Likely a much longer explanation than needed, but yeah, human mensons and modded material scanners do not function as intended.

**Comment by Alberyk** [comment]
Not only mesons, thermals and etc are also not working.
