### ISSUE TITLE
Biogenerator: Walking Mushrooms

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4409]
@Admin Spawn for Walking Mushrooms doesn't work #4408 
related to the above . The biogenerator has an expensive option to print mushroom pets, however when selected - it uses the resources and prints out nothing, I even checked to make sure there were no invisible mushrooms running around.

**Comment by hyperioo** [comment]
This issue is still valid. The biogenerator consumes the 1000 biomass of the pet mushroom but does not spawn it. Admin tried to spawn it manually but it does not work too (issue #4408).

Step to reproduce:
* get plants
* process them to get 1000 biomass
* click on the pet mushroom option
* nothing happens after the processing time

**Comment by fernerr** [comment]
Still cannot reproduce locally, so there's must be some other aspects at play. Perhaps something about the biogenerator gets borked along the way?
