### ISSUE TITLE
Ingested chemicals not appearing in blood stream

### ISSUE THREAD

**Issue by Moonyman** [Aurorastation/Aurora.3#4420]
Ingested chemicals and substances (any chems, alcohol, reishi, nutriments) do not show up on a mass spectrometer blood test. Makes alcohol and drug intoxication basically undetectable by technology if they were ingested (Might be intended but i feel like it isn't?)

**Comment by BurgerLUA** [comment]
The way the system works is that it only shows it if it's a medical reagent. Toxins and other things are undetectable, which is intended so death by poisoning is more viable for antagonism.

It's not a bug, but however if you think this should change I recommend making a suggestions thread about it so that other chemicals can be detected.
