### ISSUE TITLE
Drag Penguins Outside Holodeck

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#4795]
If you neck grab a penguin, you can carry it outside the holodeck. It can take a few tries, but it's possible.

![penguin](https://user-images.githubusercontent.com/12206154/40495907-1275d480-5f3e-11e8-8cf0-78edb6666075.png)

**Comment by Ornias1993** [comment]
I can so write lore to make this not a bug 👍 

" As matter and energy are interchangteable, the holodeck generates mater from the energy put into its hologenerators. During its runtime the holodeck disintegrates all created objects at the limits of each reach, but at certain times even the most trusty technologies fail and thus objects may leak byond the borders of the holodeck..."

Because Pinguins are awesome you funhating twat.

**Comment by Fortport** [comment]
So is this a bug or not?
