### ISSUE TITLE
Atmos doesn't work

### ISSUE THREAD

**Issue by soryy708** [Aurorastation/Aurora.3#4806]
On two occasions (different rounds) I had walked in to little pockets of no air, while tiles around it seem to have air.
Here's an example where a window's clearly broken (with carp inside) but no change to the atmos:
https://imgur.com/a/GdNQknD
(game ID: bUy-a2VR)

**Comment by Ornias1993** [comment]
I find your report a tad lacking in terms of informational value.
Was there any lag? How many people where on? Where there more leaks and or explosions happening?

Besides the tile should be something like "Atmos not processing on certain tiles", because atmos is obviously still working, just missing a tile or two when running.

I actually never bothered to look into atmos in Aurora yet, but I expect it to be ZAS based. In that case, it seems that those tiles are just not put into the right ZAS zone

**Comment by soryy708** [comment]
No lag, about 20 people online probably, Not aware of any more leaks or explosions.
I do believe it's ZAS based.

**Comment by soryy708** [comment]
Here's another instance of atmos not working:
https://imgur.com/a/JcanqYn

26 people online, game ID bUC-csYB no lag, explosions, or leaks.

**Comment by Ornias1993** [comment]
@soryy708 Ey thats me in that screenshot (one of the constructs) and my body 🗡 

Anyhow, atmos was working that round, it seems the shield keeps in atmosphere. I know the shield was on and it kept in the atmosphere because I ahelped it... I dont see the shield in your screenshot but I know 100% sure its on, so maybe your byond version just doesnt show the shield or something?

**Comment by soryy708** [comment]
@Ornias1993 I usually see the shield when it's on. Maybe the shield used to be on during part of that round, but was turned off?

**Comment by Ornias1993** [comment]
Still interesting, because we may have found the issue if thats the case...

**Comment by flimango** [comment]
Sometimes ZAS slows down tremendously. The devs were working on improving it but it’s difficult work from what I understand. It can cause the whole zone to stop processing for a time (meaning it will hold atmosphere even when there’s a gaping hole).
