### ISSUE TITLE
Coat racks won't display icon when jacket is open

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#4827]
At least with the detective trenchcoats found in detective cabinets.
If they are toggled so that they are unbuttoned rather than buttoned, then hung on a coat rack, the rack does not display an icon in which makes it apparent that there is a coat.

This is clearly a sign of false advertising and I will sue if it is not dealt with swiftly and ruthlessly.

**Comment by Moonyman** [comment]
the way it works is coathanger has its own dmi with sprites of hanging clothes. When a coat is hanged its icon name is taken, the same name is being looked up in a coathanger dmi and applied to the coathanger. The reason why open jacket is not being displayed is because its icon name is "detective_open" (as opposed to "detective"). The coathanger only has an icon named "coat_detective" so search for coat_detective_open returns nothing. Now i could duplicate the coat sprite in the coathanger dmi and name it coat_detective_open and do the same stuff with all other open coats if needed which would fix the problem, there's plenty of space in the dmi currently. But i somehow feel crowding the dmi with sprite duplicates is a sub-optimal long-term solution.

**Comment by MarinaGryphon** [comment]
My current solution to this is having it set them to closed when they're hung up.
