### ISSUE TITLE
Holodeck does not posess a powerzone

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4982]
Installing lights within the holodeck doesnt work, and you cannot make an APC within due to holofloor being unremoveable.

**Comment by XanderDox** [comment]
@Pratepresidenten I believe I asked Lohikar about this awhile ago. because of how the holodeck works, you can't have permanent props like lights or APCs.

The holodeck works by cutting the deck-choice from the Odin map, and pasting it into the holodeck. There's no way to selectively do this to leave lights in tact, so this is why the holodeck relies on hall power and lighting.
