### ISSUE TITLE
Crate despawning when alt-clicked

### ISSUE THREAD

**Issue by soryy708** [Aurorastation/Aurora.3#5090]
I was pulling a (normal, grey) crate full of materials from mining.
I placed it in the corner (see [image](https://i.imgur.com/jpgfzHz.png))
and alt-clicked to see what's on the turf below the crate,
and when I was about to click the crate to open it - it despawned!

I adminhelped and NursieKitty said:
1. There were no error logs
2. The crate is nowhere to be found (not even different z-levels)

Game ID: bVH-c3uf

**Comment by BurgerLUA** [comment]
I'm laughing pretty hard right now because I know exactly what happened. This bug has existed for a while and I keep forgetting to report it.

I was dragging the crate on top of the counter. The roboticist then took the materials and dragged them to robotics. The progress bar was still there, and after it ended, it moved the materials on top of the science desk. There were no checks during that progress bar to check if it was still moved.

**Comment by soryy708** [comment]
Ha! That's pretty epic, and should be a trivial fix no?
