### ISSUE TITLE
Crates on a cargo tug aren't cleared from the trolley when deleted

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#560]
Place large wooden crate onto cargo tug
Break open crate with crowbar.

The crate qdels itself, but isnt actually destroyed, it just goes to a null location. The trolley it was on continues to hold a reference to it in the 'load' var.

Clicking the trolley to unload it brings the crate back, allowing it to be broken again. a few times actually, garbage collection seems to catch up to it eventually but it takes a while. The crate can be broken about 7 more times if you're quick before the engine throws an error: 
## TESTING: GC: -- [0x201873f] | /obj/structure/largecrate/hoverpod was unable to be GC'd and was deleted --

and then ites gone

**Comment by skull132** [comment]
It isn't necessarily a bug, this is how qdel() works. The principle is: in order to avoid amazing lag from mass deletions during things like explosions, qdel() queues up the deletions instead. Upon immediately calling qdel() on an object, that object will be teleported away to a null location by default.

It is up to the specific object's child code (specifically: the definition of the `Destroy()` proc) to make sure that any and all special circumstances are also filled. **Or** you have the designated holder of that object check for `x.GCDestroyed` and then set references to null as necessary.

In this case, since a shitload of difference objects could be loaded onto the trolley, it'd be best to do the latter. In any proc that uses the item that is loaded onto the trolley, do something like this first:
```
if (item_on_trolley && !isnull(item_on_trolley.GCDestroyed))
    item_on_trolley = null

// Carry on with the rest of the code here.
```
