### ISSUE TITLE
Burning paper with a welder burns your eyes.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#5604]
This doesnt make any sense. You're igniting paper, not fusing metal.

**Comment by MarinaGryphon** [comment]
The intensity of the welder should be the same regardless. If you look at a lit welder in real life, period, I'm pretty sure you'd hurt your eyes.

**Comment by TheOrleans** [comment]
> The intensity of the welder should be the same regardless. If you look at a lit welder in real life, period, I'm pretty sure you'd hurt your eyes.

Actually... no.

If you look at a welder in real life... you see nothing. A real welding tool is not like the sprite, you don't see fire coming out of it

Just check this video, the sparks that damage your vision come out when the welding tool makes contact with the metal, not before, not after, only during the contact.

**Comment by Sindorman** [comment]
Yeah, but the real life welder use electrical arc welding where you attach one wire to ground the material, and another wire is electrode. There is another way of welding - what our game uses, blowtorch - it doesn't require wires to be connected, but it still produces sparks. Now of course it won't produce the sparks when you lit cigarette on fire, but just starting at the fire from the blowtorch hurts your eyes, which is why it is legit

**Comment by MarinaGryphon** [comment]
You can change the intensity of real-life blowtorches, so that actually makes sense. This should maybe be fixed.
