### ISSUE TITLE
Creating new characters carries existing data over

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#600]
When you hit 'new character' in the lobby all the information from the currently loaded character is shifted over. It would be better if an empty character page was used instead.

**Comment by skull132** [comment]
Yup, I found this out relatively recently actually.

I'm gonna add better notification on how character data control is handled, plus more stats about chars at some point. This will be one of the changes I'll be doing.

**Comment by NanakoAC** [comment]
I have to disagree with the OP, i think copying over the information is a good idea.

I would say though, as you seem to agree, that people should be notified that this is happening. So you don't get new unathi characters with flavour text about their hair *cough*

**Comment by skull132** [comment]
@NanakoAC Easy enough to put in the option of, "Yes, I want to keep the data and I won't be confused as fuck about it." Just that, there should be a default option that wipes everything, otherwise people get confused, as the only notification you get is a different gender and name. Both of which can be overlooked quite easily, so there's not enough feedback to the player as to wtf is going on.

**Comment by Talkarcabbage** [comment]
There's a larger issue that comes from this. Selecting an existing character of a different race, then making a new character, you end up with a 1 year old abomination like...
https://puu.sh/qb8eK/ad79484381.png
