### ISSUE TITLE
Phoron Salt Grenade makes negative boom

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#6112]
**The Grenade**
120u Phoron 75K (Reaction minimum temperature is 73k)
60u salt 678.13k (Reaction minimum is 678k)

This mixture of chemicals will cause a cold reaction within the phoron salt. That means instead of turning into a fireball, it explodes due to it falling bellow the stable temperature. 

It made a negative explosion.

[![Screenshot from Gyazo](https://gyazo.com/7b5d8f3393188a4b567dfe9dd9303ba7/raw)](https://gyazo.com/7b5d8f3393188a4b567dfe9dd9303ba7)

**Comment by MarinaGryphon** [comment]
This is intended. It simply wasn't strong enough to cause a big explosion, since they were just barely over the threshold. An explosion radius of -1 means don't explode, an explosion radius of 0 means explode on just one tile. If you were holding the beaker it would've flashed you, for example. Not a bug.
