### ISSUE TITLE
pAI glitches- an assortment of things.

### ISSUE THREAD

**Issue by XenosTiger** [Aurorastation/Aurora.3#661]
Apparently, pAIs are really glitchy on this server. You get no choice what device you show on- press "Yes" on one pAI request, and you're sent to two or three other devices, too. Ghosting while you're a pAI will show you still being on whatever device you were previously on, even when you get on a new person's device. And, I think my camera was following the wrong person after doing that?

Quote from me: following Jack Mitchell.... while I was actually on Ariana's device... but I was shown on Gabriel's device.

**Comment by skull132** [comment]
If my understanding is of the bug is correct. This isn't a bug.

When you accept a request and present a personality, it will be broadcast to _all_ devices. Such is its design, and such is the easiest way to go about completing it.

And _after_ you get accepted, unless the users of the other devices _refresh_ their UIs, you will still show up on their devices as a candidate. This is also fine, it's a lazyness/effort thing (it's a bitch to find out whose UIs we should be refreshing, so we just don't).

The final part is what I'll need to test, though I think it should already be working fine. Basically, what should happen: the first person who clicks you gets you. If it bugs out whereby it drags you to another device _after_ you're been already claimed, then that's a bug. Can you confirm that that is exactly what happened, or not?

**Comment by SierraKomodo** [comment]
Based on what occured (I had one of the pAIs that claimed Xenos personality), I think he got dragged into a second pAI device after already being claimed - We both brought up our pAI devices at about the same time I'm assuming, so he was listed for all of us, and we all clicked to claim him.

**Comment by NanakoAC** [comment]
fixed by #666
