### ISSUE TITLE
Duplicating Meatballs

### ISSUE THREAD

**Issue by SimonTheMiner** [Aurorastation/Aurora.3#6736]
You can duplicate meatballs in the microwave, discovered after I accidentally put flour in said meatball and then microwaved it. Will produce 3 total which can continue to produce more meatballs

**Comment by OneOneThreeEight** [comment]
Probably because the regular meatball with no other reagents recipes itself directly into one cooked meatball. Injecting something into it, even water for instance, will delete the meatball and return 3 meatballs, as the usual way to make uncooked meatballs produces 3 of them.

Fixable. Will try to fix.

**Comment by OneOneThreeEight** [comment]
Not a bug, actually.

![image](https://user-images.githubusercontent.com/11053780/61578458-3d958880-aac5-11e9-8f7d-21f390e9ec74.png)

RECURSIVE MEATBALLS. Working as intended, can safely say.

**Comment by skull132** [comment]
Not a bug.
