### ISSUE TITLE
Ovens preheat horrifically slowly and lose heat rapidly, deep fryers only reach 87.6% efficiency at maximum temperature

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#7172]
Following the merge of #7164 

![4WdCBXn](https://user-images.githubusercontent.com/44004468/66875423-412d9400-ef7c-11e9-8b9d-ea76cefce62f.png)
Fryer at maximum overdrive. The oven itself reaches 100% efficiency when it reaches 200°C.

Ovens function as they should now, they just take a million years to cook anything for the first half an hour after you show up, or for half an hour after you accidentally walk away for a minute with the door open. This seems like it would be bad for business. Neither one could be upgraded at all, as a side note, but that might be more user error than anything.

**Comment by JohnWildkins** [comment]
Fryer is (mostly) intentional - the math code sucks behind it, but it's because you haven't filled the oil tank. Even so you'll only get to like 97% efficiency or something, because again, the code is absolutely esoteric. I'll see if I can't make that less awful.

Also, yeah, it didn't occur to me at the time to change but the oven door venting is absolutely brutal. I'll see about bringing that way down to a reasonable value and looking at round-start cook times.

**Comment by sheeplets** [comment]
Making the baseline 80-100% and having it scale upwards with preheating would be appreciated, only because no one wants to wait at the counter for ten minutes while their pizza bakes because some idiot chef (who was probably me) left the door open.
