### ISSUE TITLE
Using "de admin" removes your ability to send to AOOC while antag

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#751]
However you can still read AOOC messages.

**Comment by skull132** [comment]
Unable to replicate.

I deadminned myself, and couldn't see AOOC messages until I readminned myself.

**Comment by Bedshaped** [comment]
I'll do a bit of testing and update later.

**Comment by skull132** [comment]
By chance, did you mean deadminning while _being_ an antag?

**Comment by Bedshaped** [comment]
yeh :^)

>

**Comment by skull132** [comment]
_There_ we go. Okay, that is actually a bug, yes.

Need to think of a decent way to handle this, because AOOC is a client bound verb, meaning it gets removed whenever you disconnect, or when admin verbs (all of which are client bound) are stripped. The alternative would be making it a mob bound verb, though, this may end in odd behaviour as well, for example, when you ghost or what not. Hm.

**Comment by SierraKomodo** [comment]
What about making it both, with the checks doing a 'mob' OR 'client' pass check wherever it just checks for the client's flag? That should cover both cases, albeit being a relatively lazy fix.
