### ISSUE TITLE
Donut Boxes cannot hold 6 donuts

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#7599]
For some reason, donut boxes are now only able to hold four donuts instead of their signature six. This happens to at least crafted donut boxes and it's happened in several rounds now.

**Comment by Doxxmedearly** [comment]
Just tested, confirmed. Only seems to happen for crafted donut boxes. Likely related to #7550

**Comment by Nero-07** [comment]
Took a quick look, I think it's somehow because crafting makes a special empty box that starts with null contents. Might have to change that to 0. Will investigate when I'm home.

**Comment by Doxxmedearly** [comment]
@Nero-07 Likely it's because the box/empty has the default storage space of 8, and donuts are w_class 2. The max_storage_space = 12 was removed in #7550. Even if it has 6 slots, the contents won't exceed the max_storage_space (Like how wallets behave). Readding that should fix the issue. I will get to it if you don't.

**Comment by Nero-07** [comment]
Go right ahead

**Comment by Doxxmedearly** [comment]
Shouldn't. The paths are weird. storage/fancy/donut is what's mapped in and starts full. I don't have any explanation as to why those ones can fit all 6 (probably has to do with you theory about starting with contents, but it works on testing, so I'm not gonna poke at it).

Crafted ones are storage/fancy/donut/empty. Setting it to max_storage_space = 12 won't touch the parent path, but even if it did, it wouldn't change that they work.
