### ISSUE TITLE
Reagent containers vanish when emptied.

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#8353]
Sometimes when you finish drinking from a glass or something similar, it just straight up vanishes entirely.

**Comment by Doxxmedearly** [comment]
Almost 100% sure this is caused by #8285 
This moved the on_consume() proc (which deletes src when there are no reagents) from being defined at` reagent_containers/food/snacks` to just` reagent_containers/food`. Drinking glasses are now affected by on_consume() since their path is `reagent_containers/food/drinks`, so when they no longer contain reagents, they are deleted.
 `reagent_containers/food/drinks` will need a unique handling of on_consume().

**Comment by Doxxmedearly** [comment]
I'll fix this tonight
