### ISSUE TITLE
Point To verb list populated with internal organs

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#842]
![Point To verb population](https://puu.sh/qUmcL/e3c109fd7e.png)

**Comment by skull132** [comment]
Not sure if worth fixing. Organs are objects in a mob. So it's grabbing
them.

**Comment by Bedshaped** [comment]
I figured a simple `if (isorgan()) continue` would fix it

**Comment by SoundScopes** [comment]
If you were to point to your heart or someone elses heart, you would point towards the general location of the heart at the chest. This can add a little more RP to things if people choose to use it.

**Comment by SierraKomodo** [comment]
@SoundScopes But does it actually say you pointed to XYZ's heart, or does it just say you pointed to heart?

**Comment by Bedshaped** [comment]
It doesn't say anything at the moment if you select an organ. Because it only lists your own organs.

**Comment by SoundScopes** [comment]
Ok went and read what it does

Your idea of `if (isorgan()) continue` wouldn't work as the verb is using view() which is a byond specific proc. It will collect everything in view and everything in usr.contents (usr is the person that called the proc not the object that owns the proc) using oview() or would get the suggected result.

The reason the message doesn't come up is because because of this line
 `if(!src || !isturf(src.loc) || !(A in view(src.loc)))  return` 
which basicly stops you from being able to actually point at it.

@skull132 I would class this a bug because the code literately stops you from being able to point at them if selected. Already got it fixed if you decide.

**Comment by skull132** [comment]
Is this still a thing after Nanako's update for the point to verb?

**Comment by SoundScopes** [comment]
It's still a thing
