### ISSUE TITLE
Focusing lens, weapon part lacking sprite.

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#8564]
Complete laser prototypes all use the default sprite when finished.
Parts are invisible but working.
Laser modulator for example.
It lacks both an inhand and on floor sprite.  Still works though, pretty sure it used to have a sprite.

**Comment by robovelcro** [comment]
![bugged part](https://user-images.githubusercontent.com/17680257/84692010-12b5ed80-af3d-11ea-953d-b2e908374ece.png)
Sadly this issue seems to have re-arisen. Parts like the Capacitor and Focusing Lens do not have an in-hand or floor sprite (although the lens does still take up the normal space in containers), but the parts continue to show up in the right-click menu and also function perfectly fine once attached.
