### ISSUE TITLE
Request consoles can contact Science for supplies but not for assistance

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#8681]
Science's request console is not on the "Request Assistance" list

**Comment by Sparkyhotdog** [comment]
Don't think this is a bug. The requests consoles (From the brief look I took earlier in-game) have entirely different lists for which consoles they can send assistance or supply requests to. I think this is because you don't tend to ask security for supplies like you do cargo, and vice versa for assistance. In other words, it's not meant to be there.

**Comment by JohnWildkins** [comment]
Intentional.
