### ISSUE TITLE
Explosive implants are not detonating.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#8924]
Attempted to activated explosive implant with the phrase _It's overr now._ , but the implant did not go off. Not sure if it's a problem with there being a . or an ' in there but it definitely needs to be looked into

**Comment by Doxxmedearly** [comment]
Can't replicate because you can't set the phrase to have ' in it; it will automatically remove it (and tells you such in your note and the notification when you set the phrase). My guess is that was just missed since it doesn't really tell you you can't do it.
That said, I'll see if I can have it allow certain punctuation.
