### ISSUE TITLE
Dionaea "Check Light Level" goes into decimals.

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#896]
http://i.imgur.com/F6f514r.png?1
Not really necessary. Since it's a user-end verb, it doesn't really need such precision, and rounded values would be much more readable.

**Comment by skull132** [comment]
I don't know if it should even exist as a verb? It looks like a debug verb: light level is already visible from, you know, looking at the area around you. You don't need a verb telling you the exact values.

**Comment by NanakoAC** [comment]
Its not entirely clear from looking at the area around you, because the light you recieve from sources is affected by the state of your light receptor, and the influence of restricted lightsources.

That verb is a representation of the diona's internal sense, so they can tell whether or not an area is safe, and we dont get a ton of bug reports saying 'halp im in light but dying'

**Comment by NanakoAC** [comment]
fixed by #926
