### ISSUE TITLE
Maintenance Drone Self Diagnostics don't work

### ISSUE THREAD

**Issue by MineAndCraft12** [Aurorastation/Aurora.3#9351]
As a Maintenance Drone, the Self Diagnostics menu will always show zero damage on all components, even if the armor plating is obviously damaged or the self diagnostic component itself is damaged. The drone can get damaged to the point that it struggles to stay online, and Self Diagnostics will still show zero damage across all systems.

**Comment by synystersparx** [comment]
In what situation is the armor plating obviously damaged? Same question for the self diagnostic component.

**Comment by MineAndCraft12** [comment]
In every case since I've started playing maint drone a couple weeks ago.

In the instance that prompted me to write this report, I'd been attacked by about five or six separate carp, the GUI health status indicator (where it says "Good", "Poor", "Bad", etc) had turned to static, plus the Examine verb showing visual dents on the plating. I also had randomly lost power for a few seconds, but I may have been crushed by a door in that instance.

If I remember right, the health status indicator on the GUI is tied to the diagnostic unit itself, right? Yet with all this, the diagnostic unit still displays zero points of damage on all parts.

**Comment by synystersparx** [comment]
I can't remember now, I think the GUI is just total damage, similar to the Hull Integrity part of the stat tab. 

From what I remember of the code, maintenance drones don't take internal component damage, because they cannot be opened, thus their components cannot be repaired. So any damage should just be fixable by a blow torch to the outside.

There are a few options here. Take the Self Diagnosis verb away from maintenance drones to try to help some of the confusion, or just change the display as a maintenance drone to display hull integrity only, or something like that. I asked in the code dungeon channel on discord and didn't get a response.
