### ISSUE TITLE
Picking up a gun already targeting someone results in odd behvaiour

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#942]
Dropping a gun while targeting someone (i.e. due to being knocked over/winded) results in whoever picks up the gun being treated like they're targetting that same person, even though they aren't. (Usually results in 'You refrain from firing' messages or random misfires)

**Comment by FirinMaLazors** [comment]
Being weakened or paralyzed (winded) stops the targeting.  There's a number of procs on mob/living that stop aiming (see "cancel_aiming") in appropriate situations.  However, I wasn't able to test what happens if a target moves after picking up a gun that was dropped while targeting.  This should be tested.

**Comment by JohnWildkins** [comment]
Tested extensively, no longer seems to be an issue.
