### ISSUE TITLE
Airlock Doors Take Two Minutes To Disassemble I Guess

### ISSUE THREAD

**Issue by crunchypretzels** [Aurorastation/Aurora.3#9937]
So, originally, emagged/pried open doors just required themselves to be crowbarred shut, wire bolted, and then crowbarred again to remove the broken electronics. They NOW require you to, after crowbarring and bolting them, use your welder to cut through the bolt panel and bolts themselves(despite the text saying they need to be dropped?), and then pry out the electronics, the cutting through of the bolt panel/bolts taking a grand total of _eighty seconds_ just to fix a single door.

I'm told this is what needed to be done with secure doors in the past, which is fine, but the text saying I need to drop the bolts and then spending eighty seconds watching my spaceman cut through the bolts I just dropped makes me think this is in error. The airlocks in question were various ones across science, namely the hallway/break room, maint tunnels, and RnD lab.

**Comment by FirinMaLazors** [comment]
I think so too.  It appears to be a quirk of https://github.com/Aurorastation/Aurora.3/pull/9379 not letting you try to fix a door if it's unbolted.  So you had to close and weld, and THEN bolt a door to fix it... for some raisin.  But emagged doors were bolted open, and you can't very well close them cause... y'know... they're broken and bolted, so emagged airlocks were unfixable.

So then https://github.com/Aurorastation/Aurora.3/pull/9819 comes in, makes emags not bolt doors, just makes them open and broken, and makes it so that a door has be closed AND welded AND *still* bolted AND the bolts have to be cut, whether a door is broken or not (you already have to cut the bolts of broken bolted doors to do anything to them!).

I dunno, it's a mess.  Ugh.  I'll try to fix this.

**Comment by Hockaa** [comment]
> I'm told this is what needed to be done with secure doors in the past, which is fine, but the text saying I need to drop the bolts and then spending eighty seconds watching my spaceman cut through the bolts I just dropped makes me think this is in error.

I made it so that you had to cut through the bolts because - in my mind - it felt like the idea was that on broken airlocks the bolts just got all jagged and messed up and jammed, hence the message saying that "the bolts are in the way" or somesuch, so you just have to completely clear them out to get rid of the bolts in front of the electronics.

I was actually considering reducing the time it takes to cut out the bolts though, because it does take an immense amount of time to repair a single airlock just because of that welding process, which should've just been as simple as changing a number on a proc somewhere (though I hadn't looked into it at all yet) but it looks like Firin has already made a PR so I guess I don't have to.

When I sorted out the emagging PR, I felt it was more appropriate that you had to go about it the same way, but I wasn't aware of quite how long it'd actually take you to get through multiple airlocks, because I was only doing quick tests on the one.

**Comment by FirinMaLazors** [comment]
@Hockaa Geeves said he can't remember if he intended that change, and the way I set it to is how it was previously, and how it appears to be done on other servers.
Also, sorry for the rude language, I was kinda stressed out after trying to figure out how this worked and why these changes were made.

**Comment by Hockaa** [comment]
> @Hockaa Geeves said he can't remember if he intended that change, and the way I set it to is how it was previously, and how it appears to be done on other servers.
> Also, sorry for the rude language, I was kinda stressed out after trying to figure out how this worked and why these changes were made.

No hard feelings - also, I do prefer the old way of doing it (the way you're changing it back to), I just kept it the new way because I thought it was intended by Geeves. Cheers for doing the PR.
