### ISSUE TITLE
Firearms control program fails catastrophically

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#9980]
![image](https://user-images.githubusercontent.com/22651198/93008619-5fa96000-f53c-11ea-9edb-36c417318a32.png)

The firearms control program does not load. This bricks the console, as the program cannot be exited. Force loading resources does not fix the problem.

**Comment by Arrow768** [comment]
Currently investing that.
For now just get a engineer to remove a vital part and reinstall it.
That will reset it.

**Comment by Zelmana** [comment]
This is still such a big issue.

We have to end up using Code Yellow in order to use lethals.
Code Blue does not allow for use of lethals. Often times there is only one Command staff present, making Blue-As-Red Codes extremely common.

Without the firearms control module, this entire PR is crippling security capability.

**Comment by niennab** [comment]
I can confirm this is still happening.

**Comment by JohnWildkins** [comment]
apparently it stopped breaking, amazing
re-open if it rears its ugly head again
